### ISSUE TITLE
problem when executing without aligning images

### ISSUE THREAD

**Issue by ppissias** [akdeniz-uzay/A-Track#13]
Hi! 
I wanted to post a little issue I faced, which is that when I use for the first time the -a option (not to align the images) then the process fails.

I am using aligned images so there is no need to align again. 

If, however, I use the option -a even once, then the problem goes away: 

Below is an exert from running atrack for the first time on a set of images with the -a option (fails). Then running it without the -a option (ok) and then running it with the -a option (ok). 

Thank you in advance,
Petros
 
```
osboxes@osboxes:~/soft/atrack$ python3 atrack.py -a /home/osboxes/soft/img-test/ --skip-mpcreport
WARNING: AstropyDeprecationWarning: block_reduce was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]
WARNING: AstropyDeprecationWarning: block_replicate was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]

Creating catalog files... Complete!
Catalog files are saved as *affineremap.pysexcat.
Elapsed time: 0 min 0 sec.

Building master catalog file... Complete!
Master catalog file is saved as master.pysexcat.
Elapsed time: 0 min 0 sec.

Detecting candidates... Complete!
Candidates for each image are saved as *affineremap.cnd.
Elapsed time: 0 min 0 sec.

Detecting moving objects...

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/osboxes/soft/atrack/asteroids.py", line 356, in detect_segments
    partition = partitions(workload)[int(processor)]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/osboxes/soft/atrack/asteroids.py", line 511, in detect_lines
    pool.map(detect_segments, cmds, 1)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "atrack.py", line 170, in <module>
    lines = asteroids.detect_lines(outdir, fitsdir)
  File "/home/osboxes/soft/atrack/asteroids.py", line 514, in detect_lines
    detect_segments((catdir, fitsdir, 0))
  File "/home/osboxes/soft/atrack/asteroids.py", line 356, in detect_segments
    partition = partitions(workload)[int(processor)]
IndexError: list index out of range
osboxes@osboxes:~/soft/atrack$ python3 atrack.py /home/osboxes/soft/img-test/ --skip-mpcreport
WARNING: AstropyDeprecationWarning: block_reduce was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]
WARNING: AstropyDeprecationWarning: block_replicate was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]

Aligning images... Complete!
Aligned images are saved as *affineremap.fits.
Elapsed time: 0 min 4 sec.

Creating catalog files... Complete!
Catalog files are saved as *affineremap.pysexcat.
Elapsed time: 0 min 5 sec.

Building master catalog file... Complete!
Master catalog file is saved as master.pysexcat.
Elapsed time: 0 min 6 sec.

Detecting candidates... Complete!
Candidates for each image are saved as *affineremap.cnd.
Elapsed time: 0 min 12 sec.

Detecting moving objects...


Moving object detection completed.
Elapsed time: 0 min 28 sec.
========================================================

MOVING OBJECTS:

ObjectID FileID Flags     x        y      R.A. (J2000) ... Background   Mag    MagErr  FWHM Elongation  Sky Motion 
                         pix      pix                  ...     ct       mag     mag    pix             arcsec / min
-------- ------ ----- --------- -------- ------------- ... ---------- -------- ------ ----- ---------- ------------
       1      0     3  605.1382 692.7117 18:18:45.4532 ...   1638.459 -14.2136 0.0076 46.75      1.883         0.12
       1      2     0  579.6606 674.6077 18:18:48.8527 ...   1639.727 -10.7200 0.0335  8.28      1.662         0.12
       1      3     3  611.3987 698.2013 18:18:44.4365 ...   1628.014 -11.7545 0.0187 11.34      1.675         0.12
       1      4     0  509.9719 624.7684 18:18:58.2095 ...   1596.471 -11.0898 0.0293  7.99      1.646         0.12
       1      4     3  613.7111 700.4058 18:18:44.0302 ...   1628.215 -13.1827 0.0118 31.63      1.419         0.12
       2      0     3  647.5764 668.6549 18:18:49.2387 ...   1667.003 -11.6909 0.0201 12.06      1.701         0.52
       2      3     0  637.0912 572.9730 18:19:06.0125 ...   1650.647  -9.9202 0.0517  4.36      1.251         0.52
       2      4     0  642.0468 617.5005 18:18:58.2056 ...   1670.842  -9.4873 0.0654  5.53      1.364         0.52
       4      1     2 1223.9995 632.0355 18:18:50.0897 ...   1524.875  -8.9934 0.0473  1.99      1.197         0.59
       4      3     0 1205.1390 740.8665 18:18:31.3378 ...   1508.630  -8.5291 0.1135  4.48      1.243         0.59
       4      4     0 1214.4993 686.9253 18:18:40.6322 ...   1515.009  -8.2646 0.1102  2.86      1.569         0.59
========================================================

UNCERTAIN OBJECTS:

ObjectID FileID Flags    x        y      R.A. (J2000) ... Background   Mag   MagErr FWHM Elongation  Sky Motion 
                        pix      pix                  ...     ct       mag    mag   pix             arcsec / min
-------- ------ ----- -------- -------- ------------- ... ---------- ------- ------ ---- ---------- ------------
       3      1     0 867.9043  42.3083 18:20:36.1857 ...   1579.002 -8.4019 0.0998 3.46      1.334         0.01
       3      3     0 867.5408  41.8073 18:20:36.2765 ...   1578.461 -9.3410 0.0700 4.03      1.242         0.01
       3      4     0 868.3584  42.7328 18:20:36.1073 ...   1574.120 -8.8675 0.0802 3.55      1.147         0.01
       5      2     3 643.0405 618.4986 18:18:58.0222 ...   1678.731 -9.7712 0.0534 3.58      1.242         0.07
       5      3     0 663.3389 606.4625 18:18:59.9241 ...   1671.506 -9.4786 0.0622 5.37      1.985         0.07
       5      4     0 647.5551 615.7062 18:18:58.4653 ...   1672.330 -9.4462 0.0685 7.27      1.857         0.07

A-Track has detected 0 moving objects and 0 uncertain objects.

Creating PNG files...

/home/osboxes/soft/img-test//atrack/L_2020-08-17_22-44-18_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_22-47-18_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_23-00-50_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_23-26-29_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_23-46-04_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.

PNG conversion completed.
Elapsed Time: 0 min 30 sec.

Creating GIF (animation) file...
/home/osboxes/soft/img-test//atrack/animation.gif created.
Elapsed Time: 0 min 30 sec.

osboxes@osboxes:~/soft/atrack$ python3 atrack.py -a /home/osboxes/soft/img-test/ --skip-mpcreport
WARNING: AstropyDeprecationWarning: block_reduce was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]
WARNING: AstropyDeprecationWarning: block_replicate was moved to the astropy.nddata.blocks module.  Please update your import statement. [astropy.nddata.utils]

Creating catalog files... Complete!
Catalog files are saved as *affineremap.pysexcat.
Elapsed time: 0 min 1 sec.

Building master catalog file... Complete!
Master catalog file is saved as master.pysexcat.
Elapsed time: 0 min 1 sec.

Detecting candidates... Complete!
Candidates for each image are saved as *affineremap.cnd.
Elapsed time: 0 min 7 sec.

Detecting moving objects...


Moving object detection completed.
Elapsed time: 0 min 25 sec.
========================================================

MOVING OBJECTS:

ObjectID FileID Flags     x        y      R.A. (J2000) ... Background   Mag    MagErr  FWHM Elongation  Sky Motion 
                         pix      pix                  ...     ct       mag     mag    pix             arcsec / min
-------- ------ ----- --------- -------- ------------- ... ---------- -------- ------ ----- ---------- ------------
       1      0     3  605.1382 692.7117 18:18:45.4532 ...   1638.459 -14.2136 0.0076 46.75      1.883         0.12
       1      2     0  579.6606 674.6077 18:18:48.8527 ...   1639.727 -10.7200 0.0335  8.28      1.662         0.12
       1      3     3  611.3987 698.2013 18:18:44.4365 ...   1628.014 -11.7545 0.0187 11.34      1.675         0.12
       1      4     0  509.9719 624.7684 18:18:58.2095 ...   1596.471 -11.0898 0.0293  7.99      1.646         0.12
       1      4     3  613.7111 700.4058 18:18:44.0302 ...   1628.215 -13.1827 0.0118 31.63      1.419         0.12
       2      0     3  647.5764 668.6549 18:18:49.2387 ...   1667.003 -11.6909 0.0201 12.06      1.701         0.52
       2      3     0  637.0912 572.9730 18:19:06.0125 ...   1650.647  -9.9202 0.0517  4.36      1.251         0.52
       2      4     0  642.0468 617.5005 18:18:58.2056 ...   1670.842  -9.4873 0.0654  5.53      1.364         0.52
       4      1     2 1223.9995 632.0355 18:18:50.0897 ...   1524.875  -8.9934 0.0473  1.99      1.197         0.59
       4      3     0 1205.1390 740.8665 18:18:31.3378 ...   1508.630  -8.5291 0.1135  4.48      1.243         0.59
       4      4     0 1214.4993 686.9253 18:18:40.6322 ...   1515.009  -8.2646 0.1102  2.86      1.569         0.59
========================================================

UNCERTAIN OBJECTS:

ObjectID FileID Flags    x        y      R.A. (J2000) ... Background   Mag   MagErr FWHM Elongation  Sky Motion 
                        pix      pix                  ...     ct       mag    mag   pix             arcsec / min
-------- ------ ----- -------- -------- ------------- ... ---------- ------- ------ ---- ---------- ------------
       3      1     0 867.9043  42.3083 18:20:36.1857 ...   1579.002 -8.4019 0.0998 3.46      1.334         0.01
       3      3     0 867.5408  41.8073 18:20:36.2765 ...   1578.461 -9.3410 0.0700 4.03      1.242         0.01
       3      4     0 868.3584  42.7328 18:20:36.1073 ...   1574.120 -8.8675 0.0802 3.55      1.147         0.01
       5      2     3 643.0405 618.4986 18:18:58.0222 ...   1678.731 -9.7712 0.0534 3.58      1.242         0.07
       5      3     0 663.3389 606.4625 18:18:59.9241 ...   1671.506 -9.4786 0.0622 5.37      1.985         0.07
       5      4     0 647.5551 615.7062 18:18:58.4653 ...   1672.330 -9.4462 0.0685 7.27      1.857         0.07

A-Track has detected 0 moving objects and 0 uncertain objects.

Creating PNG files...

/home/osboxes/soft/img-test//atrack/L_2020-08-17_22-44-18_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_22-47-18_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_23-00-50_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_23-26-29_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.
/home/osboxes/soft/img-test//atrack/L_2020-08-17_23-46-04_Bin1x1_120s__10C.reg_mono_wcs_affineremap.fits converted to png.

PNG conversion completed.
Elapsed Time: 0 min 27 sec.

Creating GIF (animation) file...
/home/osboxes/soft/img-test//atrack/animation.gif created.
Elapsed Time: 0 min 27 sec.

```

**Comment by Eririf** [comment]
```
  File "atrack.py", line 170, in <module>
    lines = asteroids.detect_lines(outdir, fitsdir)
```
Because lines=[] is empty, error turns out when send to pool.map
